# Generated by Django 5.1.6 on 2025-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orderdetail_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='stripe_session_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
