# Generated by Django 5.1.6 on 2026-01-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_total_sales_product_total_sales_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_sales',
            new_name='total_order',
        ),
    ]
